spring.datasource.url=jdbc:mysql://localhost:3306/SkillLink-LocalDBv1
spring.datasource.username=root
spring.datasource.password=srujanBhat18

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

#first line connects the database server to spring-boot localhost:3306 is the sql server
#the next 2 lines are the credentials to access the database
#the 3rd line makes it so that when we make some changes in the frontend it automatically changes in the backend
#a good example is if there is no field in the db but it there in the backend it automatically adds it
#the fifth line of code prints the query in the terminal helpful in debugging only
#the 6th line says to use my sql syntax
#the final line says the port number we will use here it is 8080